### ISSUE TITLE
Add domain record functionality.

### ISSUE THREAD

**Issue by KhaledLela** [tsjost/Binero-php#3]
I don't know if this API still support, But it login successfully with me but list empty domains.

We still have domain at Binero,

If you can add new feature/functionality for control domain records so i can add/remove domain record.
Then will help us in adding subdomains using API.

**Comment by tsjost** [comment]
Sorry, as already discussed in the PR, Binero as a web host no longer exists and there's no point in relying on a **private and undocumented** API.

If you want to perform domain-related actions programmatically, you need to use an actual domain registrar and not a cheap web host, for example: https://www.nameisp.com/en/reseller/api
